name: Hitch
description: "Hitch is a university carpooling mobile app that connects students and staff to share rides, manage bookings, and split travel costs seamlessly."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.8
  country_code_picker: ^3.0.0
  flutter_otp_text_field: ^1.1.3
  image_picker: ^1.0.7
  geocoding: ^3.0.0
  http: ^1.2.1
  geolocator: ^12.0.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  camera: ^0.11.3
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground : "assets/icons/foreground.png"
  adaptive_icon_background : "assets/icons/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Jokker
      fonts:
        - asset: assets/fonts/Jokker-TRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/Jokker-Trial-Medium.otf
          weight: 500
        - asset: assets/fonts/Jokker-Trial-Regular.otf
          weight: 400
        - asset: assets/fonts/Jokker-Trial-Semibold.otf
          weight: 600
